export const projects = [
  {
    title: 'Hear Me',
    subtitle: 'Lorem Impssum',
    description: '',
    language: 'TypeScript',
    framework: 'React',
    image: './project-1.gif',
    link: 'https://hearme-app.com/',
  },
  {
    title: 'WUB',
    subtitle: 'Werkzeug und Baumaschinen',
    description: '',
    language: 'TypeScript',
    framework: 'React',
    image: './project-1.gif',
    link: 'https://app.wubmal.com/home',
  },
  {
    title: 'Persoklick',
    subtitle: '',
    description: '',
    language: 'TypeScript',
    framework: 'React',
    image: './project-1.gif',
    link: 'https://persoklick-test-env.web.app/',
  },
  {
    title: 'More Moda',
    subtitle: '',
    description: '',
    language: 'TypeScript',
    framework: 'React',
    image: './project-1.gif',
    link: 'https://app.moremoda.at/',
  },
  {
    title: 'Celsion Plus',
    subtitle: '',
    description: '',
    language: 'dart',
    framework: 'flutter',
    image: './project-1.gif',
    link: '',
  },
  {
    title: 'Kluu',
    subtitle: 'Kluu Connect',
    description: '',
    language: 'C#',
    framework: 'Xamarin',
    image: './project-1.gif',
    link: 'https://kluu-connect.com/',
  },
  {
    title: 'ImmoCeption',
    subtitle: '',
    description: '',
    language: 'C#',
    framework: 'Xamarin',
    image: './project-1.gif',
    link: 'https://immoception.net/',
  },
  {
    title: 'Immowert4You',
    subtitle: '',
    description: '',
    language: 'C#',
    framework: 'Xamarin',
    image: './project-1.gif',
    link: '',
  },
];
